image: node:latest

stages:
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

deployBackToAWS:
  only:
    - master
  stage: deploy
  before_script: 
     - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
     - mkdir -p ~/.ssh     
     - echo -e "$SSH_SECRET_KEY" > ~/.ssh/id_rsa
     - chmod 600 ~/.ssh/id_rsa
     - npm install
  script:
    - npm run build
    - ls
    - scp -i ~/.ssh/id_rsa -o "StrictHostKeyChecking=no" -r ./build/ ec2-user@3.229.129.81:/home/ec2-user/ticket-sales-front/
    - bash deploy/deploy.sh
  when: manual
